CREATE TABLE IF NOT EXISTS notification (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '通知ID',
    user_id BIGINT NOT NULL COMMENT '接收用户ID',
    project_id BIGINT DEFAULT NULL COMMENT '关联项目ID',
    type VARCHAR(40) NOT NULL COMMENT '通知类型',
    title VARCHAR(160) NOT NULL COMMENT '通知标题',
    content VARCHAR(1000) NOT NULL COMMENT '通知内容',
    target_type VARCHAR(40) DEFAULT NULL COMMENT '关联资源类型',
    target_id BIGINT DEFAULT NULL COMMENT '关联资源ID',
    target_path VARCHAR(300) DEFAULT NULL COMMENT '前端跳转路径',
    business_key VARCHAR(200) DEFAULT NULL COMMENT '防重复业务键',
    read_at DATETIME DEFAULT NULL COMMENT '已读时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
    UNIQUE KEY uk_notification_user_business (user_id, business_key),
    KEY idx_notification_user_read (user_id, read_at, deleted, created_at),
    KEY idx_notification_project (project_id, created_at),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_notification_project FOREIGN KEY (project_id) REFERENCES project (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户业务通知表';
