<script setup lang="ts">
import { ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { Plus } from "@element-plus/icons-vue";
import EmptyState from "@/components/common/EmptyState.vue";
import TaskDialog from "@/components/task/TaskDialog.vue";
import { taskApi } from "@/api/task";
import { useWorkspaceStore } from "@/stores/workspace";
import type { ResearchTask, TaskStatus } from "@/types/model";
import { BOARD_COLUMNS, TASK_PRIORITY } from "@/utils/constants";
import { formatDate, initials, isOverdue } from "@/utils/format";

const workspace = useWorkspaceStore(); const dialog = ref(false);
const columnTasks = (status: TaskStatus) => workspace.tasks.filter(item => item.status === status);
async function changeStatus(task: ResearchTask, status: TaskStatus) { try { await taskApi.updateStatus(task.id, status); await workspace.loadActiveProject(); ElMessage.success("任务状态已更新"); } catch (error) { ElMessage.error((error as Error).message); } }
async function remove(task: ResearchTask) { try { await ElMessageBox.confirm(`确定删除任务“${task.title}”？`, "删除任务", { type:"warning" }); await taskApi.remove(task.id); await workspace.loadActiveProject(); ElMessage.success("任务已删除"); } catch (error) { if(error!=="cancel"&&error!=="close") ElMessage.error((error as Error).message); } }
</script>

<template>
  <EmptyState v-if="!workspace.activeProject" title="先创建或选择一个项目" description="任务始终归属于具体的研究项目。" />
  <section v-else><header class="page-heading"><div><p>TASK BOARD</p><h2>{{ workspace.activeProject.name }}</h2><span>{{ workspace.tasks.length }} 项任务 · 按研究进程分组</span></div><el-button type="primary" :icon="Plus" @click="dialog=true">新建任务</el-button></header><div class="board"><section v-for="column in BOARD_COLUMNS" :key="column.status" class="board-column"><header><span><i :class="column.status.toLowerCase()" />{{ column.title }}</span><b>{{ columnTasks(column.status).length }}</b></header><div class="card-stack"><article v-for="task in columnTasks(column.status)" :key="task.id" class="task-card"><div class="task-top"><span :class="task.priority.toLowerCase()">{{ TASK_PRIORITY[task.priority] }}优先级</span><el-dropdown><button>•••</button><template #dropdown><el-dropdown-menu><el-dropdown-item class="danger" @click="remove(task)">删除任务</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><h3>{{ task.title }}</h3><p>{{ task.description || "暂无任务说明" }}</p><div class="task-progress"><el-progress :percentage="task.progress" :show-text="false" /><small>{{ task.progress }}%</small></div><footer><span class="mini-avatar">{{ initials(workspace.members.find(m=>m.userId===task.assigneeId)?.nickname || "待") }}</span><time :class="{overdue:isOverdue(task)}">{{ formatDate(task.dueDate) }}</time></footer><el-select :model-value="task.status" size="small" @change="changeStatus(task,$event)"><el-option v-for="item in BOARD_COLUMNS" :key="item.status" :label="item.title" :value="item.status" /><el-option label="已取消" value="CANCELLED" /></el-select></article><div v-if="!columnTasks(column.status).length" class="column-empty">暂无任务</div></div></section></div></section>
  <TaskDialog v-model="dialog" />
</template>

<style scoped>
.page-heading{margin-bottom:25px;display:flex;align-items:flex-end;justify-content:space-between}.page-heading p{margin:0 0 5px;color:#8996a9;font-size:8px;font-weight:800;letter-spacing:.18em}.page-heading h2{margin:0;font-size:27px;letter-spacing:-.04em}.page-heading span{display:block;margin-top:8px;color:#7b8799;font-size:11px}.board{display:grid;grid-template-columns:repeat(4,minmax(225px,1fr));gap:13px;overflow-x:auto;padding-bottom:10px}.board-column{min-height:540px;padding:13px;border:1px solid #e2e7ed;border-radius:15px;background:#eef1f5}.board-column>header{padding:5px 4px 14px;display:flex;align-items:center;justify-content:space-between;color:#4b586d;font-size:9px}.board-column>header>span{display:flex;align-items:center;gap:8px;font-weight:700}.board-column>header i{width:7px;height:7px;border-radius:50%;background:#8fa1b8}.board-column>header i.in_progress{background:#4d78dc}.board-column>header i.review{background:#e3ab44}.board-column>header i.done{background:#59c3b1}.board-column>header b{min-width:21px;height:21px;display:grid;place-items:center;border-radius:50%;background:#dfe4eb;font-size:8px}.card-stack{display:grid;gap:10px}.task-card{padding:17px;border:1px solid #e2e6ec;border-radius:11px;background:white;box-shadow:0 5px 14px rgba(24,42,71,.035)}.task-top{display:flex;align-items:center;justify-content:space-between}.task-top>span{padding:4px 7px;border-radius:5px;color:#416173;background:#eaf2f3;font-size:7px;font-weight:800}.task-top>span.medium{color:#936417;background:#fff1d8}.task-top>span.high,.task-top>span.urgent{color:#b34e42;background:#fde9e5}.task-top button{padding:0;border:0;color:#99a4b4;background:transparent;letter-spacing:2px}.task-card h3{margin:15px 0 7px;font-size:11px;line-height:1.5}.task-card>p{min-height:33px;margin:0;color:#8591a2;font-size:8px;line-height:1.75}.task-progress{margin:17px 0 14px;display:grid;grid-template-columns:1fr 25px;align-items:center;gap:8px}.task-progress small{color:#8590a1;font-size:7px}.task-card footer{display:flex;align-items:center;justify-content:space-between}.mini-avatar{width:25px;height:25px;display:grid;place-items:center;border-radius:50%;color:#164358;background:#77d6c6;font-size:7px;font-weight:800}.task-card time{color:#8d98a9;font-size:8px}.task-card .el-select{width:100%;margin-top:13px}.column-empty{padding:27px 0;border:1px dashed #d3dae4;border-radius:9px;color:#a8b1be;text-align:center;font-size:8px}.overdue{color:#db604d!important}.danger{color:#d45d55!important}
@media(max-width:1000px){.board{grid-template-columns:repeat(4,250px)}}@media(max-width:700px){.page-heading{align-items:flex-start;gap:14px}.page-heading h2{font-size:22px}}
</style>
